import {readFile,writeFile} from 'node:fs/promises'
const dir=new URL('./',import.meta.url)
const read=name=>readFile(new URL(name,dir),'utf8').then(JSON.parse)
const baseline=await read('server-baseline.json'),local=await read('local-integration.json'),integrity=await read('local-integrity.json'),ui=await read('ui-results.json')
const findings=JSON.parse(await readFile(new URL('../qa-2026-09-14/findings.json',dir),'utf8'))
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const fixes={
F01:'Endpoint bank soal membutuhkan izin staff; respons peserta memakai allowlist tanpa kunci, bobot, dimensi, atau konfigurasi scoring.',
F02:'Registrasi publik ditutup dengan HTTP 403. Pembuatan pengguna melalui pengelolaan admin.',
F03:'HTTP diterima khusus LAN sesuai arahan pemilik. Cookie dipindahkan ke server dengan HttpOnly; Secure dapat diaktifkan untuk tunnel HTTPS. Proteksi Origin/CSRF ditambahkan.',
F04:'Sesi disimpan di database; akun aktif dan peran terbaru diperiksa setiap request. Logout, password, perubahan peran, dan penonaktifan mencabut sesi.',
F05:'Deadline global dan subtes dikelola server. Subtes wajib berurutan, restart tidak memperpanjang waktu, dan perubahan jawaban terlambat ditolak/dibuang.',
F06:'Kegagalan scoring menyimpan jawaban dengan status failed dan success:false. Verifikasi/psikogram diblokir sampai scoring pulih; rescore tersedia bagi admin.',
F07:'Payload wajib objek berisi ID soal dan opsi yang sah. Jawaban string, array, ID asing, dan nilai opsi salah ditolak 400.',
F08:'Nama dipangkas dan wajib terisi; tanggal lahir harus tanggal kalender nyata, tidak di masa depan; panjang kolom dibatasi.',
F09:'Bobot nol dipertahankan menggunakan nullish coalescing pada tiga algoritme penilaian.',
F10:'Norma lama ditemukan, dibundel, dan dapat diimpor secara idempoten. CFIT memerlukan norma umur serta skor mentah yang tepat; fallback IQ linear/terdekat dihapus.',
F11:'Klaim undangan memakai transaksi dan row lock sehingga kuota, peserta, serta paket sesi konsisten.',
F12:'Header nosniff, frame protection, referrer policy, CSP dasar, dan no-store untuk API diterapkan.',
F13:'Runtime produksi menolak secret kosong, pendek, dan placeholder. JWT dibatasi ke HS256; fallback secret produksi dihapus.',
F14:'UUID dan filter tanggal divalidasi sebelum query; input yang dahulu menghasilkan 500 kini menghasilkan 400.',
F15:'Admin biasa tidak dapat mengubah role sendiri/superadmin, memberi system:manage, atau mendelegasikan izin yang tidak dimiliki. Endpoint sistem tetap mensyaratkan superadmin.'}
const groups=[['API lokal',local,'local-integration.json'],['Integritas lokal',integrity,'local-integrity.json'],['Browser lokal',ui,'ui-results.json'],['Alur server lama',baseline,'server-baseline.json']]
const passed=g=>g.results.filter(x=>x.status==='PASS').length
const resultTable=g=>`<table><thead><tr><th>Pemeriksaan</th><th>Hasil</th></tr></thead><tbody>${g.results.map(r=>`<tr><td>${esc(r.name)}</td><td class="${r.status==='PASS'?'ok':'bad'}">${esc(r.status)}</td></tr>`).join('')}</tbody></table>`
const html=`<!doctype html><html lang="id"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PsyEngine — Laporan Perbaikan & QA</title><style>
:root{font-family:Segoe UI,Arial,sans-serif;color:#17283b;background:#edf2f5}*{box-sizing:border-box}body{margin:0}main{max-width:1120px;margin:32px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 8px 40px #102b4212}header{background:#102f46;color:white;padding:44px}header small{letter-spacing:2px;color:#7edcd1}h1{font-size:34px;margin:12px 0}h2{font-size:23px;margin:30px 0 14px}h3{margin:0 0 12px}p,li{line-height:1.6}section{padding:0 40px 20px}.lead{font-size:18px;max-width:850px;color:#dce8ee}.cards{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:28px}.card{border:1px solid #d8e2e7;border-radius:10px;padding:20px;background:#f8fafb}.number{font-size:30px;font-weight:700;display:block;color:#076a62}.muted{font-size:13px;color:#526574}.note{padding:18px 22px;border-left:4px solid #dcac35;background:#fff9e8;border-radius:6px;margin:20px 0}.goodnote{border-left-color:#168878;background:#effaf7}table{border-collapse:collapse;width:100%;font-size:14px;margin:16px 0}th{text-align:left;background:#edf3f6}td,th{padding:12px;border-bottom:1px solid #dde5e9;vertical-align:top}td:first-child{min-width:60px}.ok{color:#076a50;font-weight:600}.bad{color:#b33c22;font-weight:600}.badge{display:inline-block;padding:4px 8px;border-radius:5px;background:#eaf6f0;color:#076a50;font-size:12px;font-weight:600}.accepted{background:#fff1d0;color:#8b6100}details{border:1px solid #dde5e9;padding:16px;border-radius:8px;margin:12px 0}summary{font-weight:600;cursor:pointer}a{color:#076c91}code{background:#eef3f6;padding:2px 5px;border-radius:3px;overflow-wrap:anywhere}footer{padding:24px 40px;color:#526574;background:#f3f6f8;font-size:13px}button{border:1px solid #8dafbd;background:transparent;color:white;padding:10px 18px;border-radius:7px;cursor:pointer}@media(max-width:700px){main{margin:0;border-radius:0}header,section{padding:24px}.cards{grid-template-columns:repeat(2,1fr)}h1{font-size:28px}table{font-size:12px}td,th{padding:8px}}@media print{body{background:white}main{margin:0;box-shadow:none;max-width:none}header{background:white;color:#102f46;padding:20px}.lead{color:#334e60}header small{color:#076a62}button{display:none}section{padding:0 20px 10px}.card,details,tr{break-inside:avoid}details{display:block}h2{break-after:avoid}a{color:inherit}footer{padding:20px}}
</style><main><header><small>PSYENGINE · QA REGRESI · 14 SEPTEMBER 2026</small><h1>Perbaikan keamanan dan integritas tes</h1><p class="lead">Perubahan tersedia di repo lokal. Alur CFIT, PAPI Kostick, dan EPPS diuji memakai data sintetis; server lama diperiksa sebagai pembanding.</p><button onclick="window.print()">Cetak / Simpan PDF</button></header>
<section><div class="cards"><div class="card"><span class="number">14</span>Temuan diperbaiki lokal</div><div class="card"><span class="number">1</span>Pengecualian HTTP LAN</div><div class="card"><span class="number">${passed(local)+passed(integrity)}</span>Pemeriksaan API lokal lulus</div><div class="card"><span class="number">3</span>Jenis tes diuji lengkap</div></div>
<div class="note goodnote"><strong>Kesimpulan: perbaikan lokal lulus pemeriksaan regresi yang dicatat.</strong><br>Hasil ini tidak menyatakan sistem bebas seluruh bug. Versi perbaikan belum diterapkan ke server. Penerimaan publik memerlukan pengujian ulang setelah deployment melalui hostname Cloudflare Tunnel.</div>
<h2>Ruang lingkup dan bukti</h2><p>QA lokal berjalan di <code>127.0.0.1:8890</code> menggunakan database terpisah <code>psy_qa_*</code>. Definisi tes disalin dari server tanpa menyalin data peserta nyata. Database yang semula dikonfigurasi repo hanya berisi soal contoh 12/10/10; setelah disamakan, pengujian memakai 46/90/225 soal.</p>
<table><thead><tr><th>Kelompok</th><th>Lulus / jumlah</th><th>Bukti</th></tr></thead><tbody>${groups.map(([name,g,file])=>`<tr><td>${name}</td><td>${passed(g)} / ${g.results.length}</td><td><a href="${file}">${file}</a></td></tr>`).join('')}<tr><td>Unit regresi + monitoring</td><td>28 / 28 + pemeriksaan monitoring lulus</td><td><a href="unit-tests.txt">Log unit test</a></td></tr><tr><td>Build produksi Node</td><td>Lihat log build final</td><td><a href="build.log">build.log</a></td></tr></tbody></table>
<h2>Hasil tiga tes</h2><table><thead><tr><th>Tes</th><th>Jawaban</th><th>Hasil sintetis</th><th>Alur</th></tr></thead><tbody><tr><td>CFIT Scale 2</td><td>46</td><td>30 benar → IQ 96 sesuai norma dewasa</td><td>Simpan, muat ulang, submit, scoring, verifikasi lulus</td></tr><tr><td>PAPI Kostick</td><td>90</td><td>90 pilihan terhitung; 18 dimensi muncul pada fixture</td><td>Simpan, muat ulang, submit, scoring, verifikasi lulus</td></tr><tr><td>EPPS</td><td>225</td><td>15 dimensi; struktur needs/matrix/consistency tersedia</td><td>Simpan, muat ulang, submit, scoring, verifikasi lulus</td></tr></tbody></table><p class="muted">Angka merupakan keluaran data sintetis untuk menguji perangkat lunak, bukan hasil asesmen seseorang. Pembandingan server lama lulus ${passed(baseline)}/${baseline.results.length} pemeriksaan. Tiga peserta/sesi sintetis server dipertahankan agar dapat ditinjau; identitas rekaman tercatat pada bukti JSON.</p>
<h2>Status seluruh temuan</h2><table><thead><tr><th>ID</th><th>Temuan awal / tingkat</th><th>Perbaikan dan status</th></tr></thead><tbody>${findings.map(f=>`<tr><td><strong>${f.id}</strong></td><td>${esc(f.title)}<br><span class="muted">${esc(f.severity)}</span></td><td><span class="badge ${f.id==='F03'?'accepted':''}">${f.id==='F03'?'HTTP LAN diterima; HTTPS menunggu':'Diperbaiki lokal'}</span><p>${esc(fixes[f.id])}</p></td></tr>`).join('')}</tbody></table>
<h2>Norma CFIT ditemukan</h2><p>Sumber berasal dari <code>gym-membership-backend/docs/soalPsikolog/data/cfit-norms.json</code> dan direferensikan seeder JavaScript lama. Salinan frontend mempunyai hash yang sama. File kini disertakan di <code>data/cfit/norms.json</code>, bukan folder publik.</p><p>Tersedia 14 kelompok umur. Norma dewasa mencakup 165–999 bulan dan skor mentah 14–43. Skor/umur di luar tabel memerlukan review admin; sistem tidak menghasilkan IQ melalui perkiraan linear atau nilai terdekat. Validitas psikometrik tabel tetap menjadi kewenangan pemilik instrumen.</p>
<h2>Catatan penerapan</h2><ol><li>Cadangkan database dan jalankan migrasi <code>0012_auth_sessions</code>; seluruh pengguna perlu login ulang.</li><li>Set JWT secret acak dan kuat. Import norma memakai <code>npm run db:seed-cfit-norms</code>; norma yang sudah ada dipertahankan.</li><li>Jangan memaksa seed soal contoh ke server. Hindari pergantian versi saat peserta masih mengerjakan tes.</li><li>LAN: <code>AUTH_COOKIE_SECURE=false</code>. Hostname publik: <code>AUTH_COOKIE_SECURE=true</code> dan <code>APP_ORIGIN=https://hostname-publik</code>, kemudian uji kembali.</li></ol><p><a href="DEPLOYMENT.md">Catatan deployment dan pengulangan tes</a></p>
<h2>Batas pengujian dan observasi lingkungan</h2><p>Pemeriksaan mencakup regresi 15 temuan, alur ketiga tes, akses akun, timer, kegagalan scoring, input invalid, dan lima klaim undangan bersamaan. Tidak mencakup uji beban besar, seluruh kombinasi browser/perangkat, image Docker end-to-end, konfigurasi tunnel, disaster recovery, atau validasi psikometrik independen.</p><p>Log proses QA sempat memuat peringatan PostgreSQL <code>57P02</code> (koneksi diputus akibat proses database lain berhenti). Pengujian berikutnya berhasil, tetapi penyebab infrastruktur belum ditentukan. Stabilitas host database perlu diperiksa sebelum penerimaan publik. Kegagalan aset browser ketika build menimpa output proses lama pulih setelah restart aplikasi.</p>
<h2>Rincian pemeriksaan</h2>${groups.map(([name,g])=>`<details><summary>${esc(name)} — ${passed(g)}/${g.results.length} lulus</summary>${resultTable(g)}</details>`).join('')}</section><footer>Disusun dari pengujian pada 14 September 2026 · Repo lokal D:\\dev\\psy-engine · Password, token sesi, dan kunci soal tidak dimasukkan ke laporan.</footer></main></html>`
await writeFile(new URL('laporan-perbaikan-qa.html',dir),html)
console.log('HTML report written')
